### ISSUE TITLE
Project Document

### ISSUE THREAD

**Issue by aidenlx** [PKM-er/obsidian-zotlit#7]
- [x] scaffold for document website
  - https://vercel.com/guides/deploying-docusaurus-with-vercel
  - https://docusaurus.io/docs/deployment#deploying-to-vercel
  - https://juejin.cn/post/7049379636261683231
- [ ] giscus support
- [ ] complete contents
  - https://www.youtube.com/watch?v=t4vKPhjcMZg
  - https://publish.obsidian.md/shellcommands/Index
  - README
    - root
    - obsidian plugin
    - Zotero plugin
  - Introduction (Features)
  - Getting Started
  - Examples
  - References

**Comment by MSBack** [comment]
An example of an ETA template would be great, as I have never tried ETA before. I made a nunjucks template for the Zotero Integration plugin which allows me to organize annotations as a bullet list, grouped by color under separate headings. I would love to implement something similar in ETA for this plugin, because it offers many more features and way better performance compared to the Zotero Integration plugin. As is, the lack of examples and documentation makes it difficult to switch over.

See my template here: [https://forum.obsidian.md/t/zotero-integration-import-templates/36310/75?u=feralflora](https://forum.obsidian.md/t/zotero-integration-import-templates/36310/75?u=feralflora)
